version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-demo"
s3_prefix = "lambda-demo"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = false
